# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  max_comments_per_review: 10
  style: educational
  strictness: medium
  praise: true
  language: ko
  
  # 파일 패턴 제외
  path_patterns:
    - "!*.md"
    - "!docs/*"
    - "!test/*"
  
  # 특정 브랜치 제외
  branch_patterns:
    - "!master"

  # 코드 스타일 규칙
  rules:
    style:
      indent: 
        enabled: true
        size: 4
      whitespace:
        enabled: true
      spacing:
        control_structures:
          before_parentheses: true
          within_parentheses: false

  # 코드 품질 관련 규칙
  categories:
    - code_style
    - best_practices
    - potential_bugs
    - naming
    - readability
